# fly.toml app configuration file generated for su on 2023-08-15T00:41:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "su"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  processes = ["app"]
